name: Data Nueron official Deployment

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: eng-dataneuron-official    
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm ci
    - run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
